[package]
name = "dotsamaworld"
version = "0.1.1"
authors = []
edition = "2021"
repository = "https://github.com/gilescope/dotsamaworld"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["normalmouse"]
# 3d mouse support (it's best not to have both features enabled at once).
spacemouse = ["bevy_spacemouse"]
normalmouse = ["bevy_flycam"]
adaptive-fps = []

[dependencies]
#sp-core = "*"
primitive-types = "0.11"
log = "0.4.14"
async-std = { version = "1.12.0", features = ["attributes", "tokio1", "async-channel"] }
async-trait = "0.1"
lazy_static = "*"
futures = "0.3.13"
#jsonrpsee-types = "*"

egui-datepicker = { git="https://github.com/HU90m/egui-datepicker.git", branch = "for-project-use", default-features = false }

#wasm-bindgen-rayon = "1.0"
#[target.'cfg(target_os = "linux")'.dependencies]

winit = { version = "*", features = ["x11"] }
bevy_flycam = { git="https://github.com/gilescope/bevy_flycam", optional = true, rev="d0075df931d4de3cbaca614cf24ecdb4d98f8756" }
bevy_mod_picking = "0.6"
hex = "*"
# bevy-inspector-egui-derive = "*"
#smoldot = { git= "https://github.com/paritytech/smoldot.git", defalult-features = false }
parity-scale-codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive", "full", "bit-vec"] }
#bevy_rapier3d = { version = "*", features = [ "simd-nightly", "parallel" ] }
bevy_atmosphere = "0.3"
palette = {git="https://github.com/Ogeon/palette.git", defalult-features= false}              # why: git ref as waiting for publish of > 0.6. perceptual color scheme LCH: https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/
fastrand = "*"
# bevy-inspector-egui = "0.10"
#serde_bytes = "0.11"
serde_json = "*"
bevy_spacemouse = { git= "https://github.com/gilescope/bevy_spacemouse.git", rev="c4240e44b4757293b4424e58836bf29f9c8e4476", optional = true }
serde = "*"
bevy_egui = "*"
egui = "0.17"

url = "*"
# async-tungstenite = "*"
async-tls = "*"
color-eyre = {version = "0.5", default-features = false }
bevy_polyline = "0.2"
# bevy_hanabi = "0.2"
# frame-metadata = "15.0.0"
frame-metadata = { git="https://github.com/integritee-network/frame-metadata.git", default-features = false, features = ["v14", "full_derive"] }

scale-info = { version = "*", features = ["serde"] }
scale-value = {  git="https://github.com/gilescope/scale-value", branch="wasm32" }
# scale-value = {path="/home/gilescope/git/scale-value" }
scale-borrow = { git="https://github.com/gilescope/scale-borrow", features = ["bitvec"], rev="32eaadb6599895928ac9ccec133940edf1da0d35" }
scale-value-to-borrowed = { git = "https://github.com/gilescope/scale-value-to-borrowed", features=["bitvec"], rev="3a5b4bab485eb87d49e5c23cecfabd0a2d7e60c8" }
# scale-value-to-borrowed = { path = "/home/gilescope/git/scale-value-to-borrowed", features=["bitvec"] }

polkadyn = { git = "https://github.com/gilescope/polkadyn" }
# polkadyn = { path = "/home/gilescope/git/polkadyn" }
 
# desub = { git = "https://github.com/paritytech/desub/" }
# desub-current = { git = "https://github.com/paritytech/desub/", branch="giles-metadata-v15" }
# bevy_kira_audio = "*"
# dolly = "0.3"
# contract-transcode = { git = "https://github.com/paritytech/cargo-contract.git" }
egui_extras = { version="0.17", features = ["image", "image"] }
image = { version = "0.24", features = ["jpeg"] }

[target.'cfg(all(not(target_env = "msvc"),not(target_arch = "wasm32")))'.dependencies]
tikv-jemallocator = "0.5"
rayon = "*"

# Dependencies for native only.
# dynamic
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono= { version = "*", default-features = false }
bevy = { version = "0.7", default-features = false, features = ["bevy_gltf", "bevy_winit", "render", "png", "jpeg"] }
# subxt = { git = "https://github.com/paritytech/subxt.git" }
open = "1"
# polkapipe = { git = "https://github.com/gilescope/polkapipe", rev="de8d332bc69a2fcbd6703fbf3c9280c74c058040", features = ["wss"]}
polkapipe = { path= "/Users/bit/p/polkapipe", default-features=false, features = ["wss"]}
async-tungstenite = { version = "0.15.0",  default-features = true, features = ["async-tls", "async-std-runtime"] }

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "*"
console_error_panic_hook = "0.1"
bevy_tasks = "0.7"
chrono= { version = "*", default-features = false, features=["wasmbind"] }
bevy = { version = "0.7", default-features = false, features = ["bevy_gltf", "bevy_winit", "render", "png", "jpeg"] }
bevy_webgl2 = "*"
getrandom = { version = "0.2.7", features = ["wasm-bindgen", "js"] }
#tracing-wasm = "*"
wasm-bindgen = "*"
ws_stream_wasm = "*"
# wasm32 branch
# polkapipe = { git = "https://github.com/gilescope/polkapipe", rev="de8d332bc69a2fcbd6703fbf3c9280c74c058040", features = ["ws-web"]}
polkapipe = { path= "/Users/bit/p/polkapipe", default-features=false, features = ["ws-web"]}

# [patch.'https://github.com/bevyengine/bevy']
# bevy = {git = "https://github.com/bevyengine/bevy//", rev="841755aaf23acfd55b375c37390daeb302c5b30b", default-features=false}

# [patch.'https://github.com/mrk-its/bevy_webgl2']
# bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2//", rev="035236b8d7ec52b8e9e20399662e89c73e4521f6", default-features=false}



#console_error_panic_hook = { version = "0.1", optional = true }

#smoldot = { git= "https://github.com/paritytech/smoldot.git", defalult-features = false }

#subxt = {git= "https://github.com/paritytech/subxt.git"}


#async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    'console',
    'Document',
    'HtmlElement',
    'HtmlInputElement',
    'MessageEvent',
    'Window',
    'Worker',
    'WebGlRenderingContext',
    'WebGlShader'
]

[profile.dev]
opt-level = 1

[profile.release]



# lto = true
# opt-level = 's'


[profile.dev.package.backtrace]
opt-level = 3
